#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyProject.Droid.Resource", IsApplication=true)]

namespace MyProject.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::MyProject.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Forms.Material.Android.Resource.Animation.EnterFromLeft = global::MyProject.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Material.Android.Resource.Animation.EnterFromRight = global::MyProject.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Material.Android.Resource.Animation.ExitToLeft = global::MyProject.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Material.Android.Resource.Animation.ExitToRight = global::MyProject.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.collectionViewStyle = global::MyProject.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.materialCheckBoxStyle = global::MyProject.Droid.Resource.Attribute.materialCheckBoxStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.materialOutlinedButtonStyle = global::MyProject.Droid.Resource.Attribute.materialOutlinedButtonStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.materialProgressBarCircularStyle = global::MyProject.Droid.Resource.Attribute.materialProgressBarCircularStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.materialProgressBarHorizontalStyle = global::MyProject.Droid.Resource.Attribute.materialProgressBarHorizontalStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.materialSliderStyle = global::MyProject.Droid.Resource.Attribute.materialSliderStyle;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.scrollViewStyle = global::MyProject.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Material.Android.Resource.Color.white_disabled_material = global::MyProject.Droid.Resource.Color.white_disabled_material;
			global::Xamarin.Forms.Material.Android.Resource.Drawable.MaterialActivityIndicatorBackground = global::MyProject.Droid.Resource.Drawable.MaterialActivityIndicatorBackground;
			global::Xamarin.Forms.Material.Android.Resource.Drawable.MaterialProgressBar = global::MyProject.Droid.Resource.Drawable.MaterialProgressBar;
			global::Xamarin.Forms.Material.Android.Resource.Id.bottomtab_navarea = global::MyProject.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Material.Android.Resource.Id.bottomtab_tabbar = global::MyProject.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.flyoutcontent_appbar = global::MyProject.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.main_appbar = global::MyProject.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.main_tablayout = global::MyProject.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Material.Android.Resource.Id.main_toolbar = global::MyProject.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.main_viewpager = global::MyProject.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Material.Android.Resource.Id.materialformsedittext = global::MyProject.Droid.Resource.Id.materialformsedittext;
			global::Xamarin.Forms.Material.Android.Resource.Id.shellcontent_appbar = global::MyProject.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.shellcontent_toolbar = global::MyProject.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Material.Android.Resource.Id.sliding_tabs = global::MyProject.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Material.Android.Resource.Id.toolbar = global::MyProject.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Material.Android.Resource.Layout.BottomTabLayout = global::MyProject.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Material.Android.Resource.Layout.FallbackTabbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Material.Android.Resource.Layout.FallbackToolbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Material.Android.Resource.Layout.FlyoutContent = global::MyProject.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Material.Android.Resource.Layout.MaterialPickerTextInput = global::MyProject.Droid.Resource.Layout.MaterialPickerTextInput;
			global::Xamarin.Forms.Material.Android.Resource.Layout.RootLayout = global::MyProject.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Material.Android.Resource.Layout.ShellContent = global::MyProject.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Material.Android.Resource.Layout.Tabbar = global::MyProject.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Material.Android.Resource.Layout.TextInputLayoutFilledBox = global::MyProject.Droid.Resource.Layout.TextInputLayoutFilledBox;
			global::Xamarin.Forms.Material.Android.Resource.Layout.Toolbar = global::MyProject.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Material.Android.Resource.String.overflow_tab_title = global::MyProject.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Material.Android.Resource.Style.AppCompatDialogStyle = global::MyProject.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Material.Android.Resource.Style.collectionViewTheme = global::MyProject.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Material.Android.Resource.Style.MainTheme = global::MyProject.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Material.Android.Resource.Style.MainTheme_Base = global::MyProject.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Material.Android.Resource.Style.scrollViewScrollBars = global::MyProject.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Material.Android.Resource.Style.scrollViewTheme = global::MyProject.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Material.Android.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox = global::MyProject.Droid.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialButton = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialButton;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialButtonOutlined = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialButtonOutlined;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialCheckBox = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialCheckBox;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialEntryFilled = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialEntryFilled;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialProgressBarCircular = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialProgressBarCircular;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialProgressBarHorizontal = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialProgressBarHorizontal;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialSlider = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialSlider;
			global::Xamarin.Forms.Material.Android.Resource.Style.XamarinFormsMaterialTheme = global::MyProject.Droid.Resource.Style.XamarinFormsMaterialTheme;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ItemsViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ScrollViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromLeft = global::MyProject.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromRight = global::MyProject.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToLeft = global::MyProject.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToRight = global::MyProject.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.collectionViewStyle = global::MyProject.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.scrollViewStyle = global::MyProject.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_navarea = global::MyProject.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_tabbar = global::MyProject.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::MyProject.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_appbar = global::MyProject.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_tablayout = global::MyProject.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_toolbar = global::MyProject.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_viewpager = global::MyProject.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_appbar = global::MyProject.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_toolbar = global::MyProject.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.sliding_tabs = global::MyProject.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Id.toolbar = global::MyProject.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.BottomTabLayout = global::MyProject.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackTabbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackToolbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FlyoutContent = global::MyProject.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.RootLayout = global::MyProject.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.ShellContent = global::MyProject.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Tabbar = global::MyProject.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::MyProject.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.String.overflow_tab_title = global::MyProject.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Android.Resource.Style.AppCompatDialogStyle = global::MyProject.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Style.collectionViewTheme = global::MyProject.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme = global::MyProject.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme_Base = global::MyProject.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewScrollBars = global::MyProject.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewTheme = global::MyProject.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox = global::MyProject.Droid.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromLeft = global::MyProject.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromRight = global::MyProject.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToLeft = global::MyProject.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToRight = global::MyProject.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Resource.Attribute.collectionViewStyle = global::MyProject.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Attribute.scrollViewStyle = global::MyProject.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_navarea = global::MyProject.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_tabbar = global::MyProject.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Resource.Id.flyoutcontent_appbar = global::MyProject.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_appbar = global::MyProject.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_tablayout = global::MyProject.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Resource.Id.main_toolbar = global::MyProject.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_viewpager = global::MyProject.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_appbar = global::MyProject.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_toolbar = global::MyProject.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.sliding_tabs = global::MyProject.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Resource.Id.toolbar = global::MyProject.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Resource.Layout.BottomTabLayout = global::MyProject.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackTabbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackToolbarDoNotUse = global::MyProject.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FlyoutContent = global::MyProject.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Resource.Layout.RootLayout = global::MyProject.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.ShellContent = global::MyProject.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Resource.Layout.Tabbar = global::MyProject.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Resource.Layout.Toolbar = global::MyProject.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Resource.String.overflow_tab_title = global::MyProject.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Resource.Style.AppCompatDialogStyle = global::MyProject.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Resource.Style.collectionViewTheme = global::MyProject.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme = global::MyProject.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme_Base = global::MyProject.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewScrollBars = global::MyProject.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewTheme = global::MyProject.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox = global::MyProject.Droid.Resource.Style.Widget_MaterialComponents_CompoundButton_CheckBox;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::MyProject.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::MyProject.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int EnterFromLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int EnterFromRight = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ExitToLeft = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExitToRight = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int collectionViewStyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int materialCheckBoxStyle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int materialOutlinedButtonStyle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int materialProgressBarCircularStyle = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int materialProgressBarHorizontalStyle = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int materialSliderStyle = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int scrollViewStyle = 2130837510;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int colorAccent = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int colorPrimary = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int colorPrimaryDark = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int launcher_background = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int white_disabled_material = 2130903044;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040002
			public const int home = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int image = 2130968579;
			
			// aapt resource value: 0x7F040000
			public const int MaterialActivityIndicatorBackground = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MaterialProgressBar = 2130968577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int bottomtab_navarea = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int bottomtab_tabbar = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int flyoutcontent_appbar = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int main_appbar = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int main_tablayout = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int main_toolbar = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int main_viewpager = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int materialformsedittext = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int progress = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int secondaryProgress = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int shellcontent_appbar = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int shellcontent_toolbar = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int sliding_tabs = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int toolbar = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int BottomTabLayout = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int FallbackTabbarDoNotUse = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int FallbackToolbarDoNotUse = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int FlyoutContent = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int MaterialPickerTextInput = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int RootLayout = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int ShellContent = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int Tabbar = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int TextInputLayoutFilledBox = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int Toolbar = 2131099657;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int icon = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int icon_round = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int launcher_foreground = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int overflow_tab_title = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppCompatDialogStyle = 2131296256;
			
			// aapt resource value: 0x7F09000C
			public const int collectionViewTheme = 2131296268;
			
			// aapt resource value: 0x7F090001
			public const int MainTheme = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int MainTheme_Base = 2131296258;
			
			// aapt resource value: 0x7F09000D
			public const int scrollViewScrollBars = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int scrollViewTheme = 2131296270;
			
			// aapt resource value: 0x7F090003
			public const int Widget_MaterialComponents_CompoundButton_CheckBox = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int XamarinFormsMaterialButton = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int XamarinFormsMaterialButtonOutlined = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int XamarinFormsMaterialCheckBox = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int XamarinFormsMaterialEntryFilled = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int XamarinFormsMaterialProgressBarCircular = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int XamarinFormsMaterialProgressBarHorizontal = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int XamarinFormsMaterialSlider = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int XamarinFormsMaterialTheme = 2131296267;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000 }
			public static int[] ItemsViewRendererTheme = new int[] {
					2130837504};
			
			// aapt resource value: 0
			public const int ItemsViewRendererTheme_collectionViewStyle = 0;
			
			// aapt resource value: { 0x7F020006 }
			public static int[] ScrollViewRendererTheme = new int[] {
					2130837510};
			
			// aapt resource value: 0
			public const int ScrollViewRendererTheme_scrollViewStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0B0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131427328;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
